apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  labels:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: bookstack
spec:
  storageClassName: zfs-local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  labels:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: bookstack
spec:
  storageClassName: zfs-local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-uploads
  labels:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: bookstack
spec:
  storageClassName: zfs-local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

