apiVersion: v1
kind: Namespace
metadata:
  name: website-2017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-2017
  namespace: website-2017
  labels:
    app: website-2017
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-2017
  strategy: {}
  template:
    metadata:
      labels:
        app: website-2017
    spec:
      containers:
      - image: ghcr.io/fluufff/website-2017:latest
        name: website-2017
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: website-2017
  namespace: website-2017
  labels:
    app: website-2017
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: website-2017
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: website-2017
  namespace: website-2017
  labels:
    app: website-2017
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`2017.fluufff.org`)
    services:
    - kind: Service
      name: website-2017
      port: 80
