apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-next
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fluufff/infra-argocd.git
    targetRevision: next
    path: charts/website-next
    helm:
      releaseName: website-next
  destination:
    server: "https://kubernetes.default.svc"
    namespace: website-next
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .spec.replicas
    - .spec.template.spec.containers[].image
  - kind: Secret
    jqPathExpressions:
    - .data
