apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-redirect-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80 default_server;
        server_name _;

        location / {
          return 302 https://fluufff.org$request_uri;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-redirect
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-redirect
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: nginx-redirect-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nginx-redirect
  name: nginx-redirect
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: nginx-redirect
  type: ClusterIP
