apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-redirect
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`fluufff.be`) || Host(`www.fluufff.be`)
    services:
    - kind: Service
      name: nginx-redirect
      port: http
