apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: bookstack
  name: bookstack
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: bookstack
      app.kubernetes.io/component: bookstack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bookstack
        app.kubernetes.io/component: bookstack
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: appkey
        - name: APP_URL
          value: {{ printf "%s%s" "https://" ( required "host is required" .Values.host ) | quote }}
        - name: DB_HOST
          value: mariadb
        - name: DB_DATABASE
          value: bookstack
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mariadb-user
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-user
              key: pass
        - name: APP_VIEWS_BOOKS
          value: grid
        - name: SESSION_LIFETIME
          value: "1440"
        - name: SESSION_SECURE_COOKIE
          value: "true"
        - name: STORAGE_TYPE
          value: local_secure
        - name: GOOGLE_APP_ID
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: google_clientid
        - name: GOOGLE_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: google_secret
        - name: MAIL_DRIVER
          value: smtp
        - name: MAIL_HOST
          value: smtp.gmail.com
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_ENCRYPTION
          value: tls
        - name: MAIL_USERNAME
          value: it@fluufff.org
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: gmail_pass
        - name: MAIL_FROM
          value: it@fluufff.org
        image: {{ required "bookstack image is required" .Values.images.bookstack }}
        name: bookstack
        ports:
        - containerPort: 8080
          name: bookstack
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: uploads
          mountPath: /var/www/bookstack/public/uploads
        - name: storage
          mountPath: /var/www/bookstack/storage
          # Because the Dockerfile specified a VOLUME here,
          # we're stuck having to create a separate pvc and mount for this.
        - name: storage-uploads
          mountPath: /var/www/bookstack/storage/uploads
        - name: cache
          mountPath: /var/www/bookstack/bootstrap/cache
        - name: mariadb-user
          mountPath: /etc/secrets/mariadb-user
          readOnly: true
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      - name: storage-uploads
        persistentVolumeClaim:
          claimName: storage-uploads
      - name: cache
        emptyDir:
      - name: mariadb-user
        secret:
          secretName: mariadb-user
          defaultMode: 0440
---
apiVersion: v1
kind: Service
metadata:
  name: bookstack
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: bookstack
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: bookstack
