images:
  vikunja: docker.io/vikunja/vikunja:0.24.6
  postgres: docker.io/postgres:18.1

resources:
  postgres:
    # startup peak: 0.09
    # peak: 0.015
    cpu: 10m
    # peak: 134M
    memory: 300Mi
  vikunja:
    cpu: 100m
    memory: 1Gi

securityContext:
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
