apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: site
  labels:
    app: site
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.host }}`)
    services:
    - kind: Service
      name: site
      port: http
