apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    {{- include "vikunja.commonLabels" . | nindent 4 }}
  name: vikunja
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`vikunja.next.fluufff.org`)
    services:
    - kind: Service
      name: vikunja
      namespace: {{ .Release.namespace }}
