apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "vikunja.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/component: postgres
  name: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/component: postgres
  ports:
  - name: sql
    port: 5432
    protocol: TCP
    targetPort: 5432
